--------------------------------------------------------
--  File created - Tuesday-December-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADJUDICATION
--------------------------------------------------------

  CREATE TABLE ADJUDICATION 
   (	ADJUDICATIONID NUMBER(8,0), 
	PROCEDURENUMBER NVARCHAR2(50), 
	CONTRACTTYPE NVARCHAR2(30), 
	MODALITY NVARCHAR2(30), 
	SOURCEORIGIN NVARCHAR2(30), 
	ADJUDICATIONTYPE NVARCHAR2(50), 
	AMOUNT NUMBER(10,4), 
	STATUS NVARCHAR2(50), 
	CREATIONDATE DATE, 
	CLOSEDATE DATE, 
	ACTIVE NUMBER(8,0), 
	FINISHDATE DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ADJUDICATIONDOCUMENT
--------------------------------------------------------

  CREATE TABLE ADJUDICATIONDOCUMENT 
   (	ADJUDICATIONDOCUMENTID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	IDENTIFIER NVARCHAR2(150), 
	NAME NVARCHAR2(555), 
	PATH NVARCHAR2(550)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ADJUDICATIONSTEP
--------------------------------------------------------

  CREATE TABLE ADJUDICATIONSTEP 
   (	ADJUDICATIONSTEPID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	STEP NVARCHAR2(150), 
	CREATIONDATE DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ADMINISTRATIVEUNIT
--------------------------------------------------------

  CREATE TABLE ADMINISTRATIVEUNIT 
   (	ADMINISTRATIVEUNITID NUMBER(8,0), 
	CODE NVARCHAR2(50), 
	DESCRIPTION NVARCHAR2(250), 
	EMAIL NVARCHAR2(150), 
	AUTHORIZER NUMBER(8,0), 
	ACTIVE CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ANNEX
--------------------------------------------------------

  CREATE TABLE ANNEX 
   (	ANNEXID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	ASSETID NUMBER(8,0), 
	QUANTITY NUMBER(10,4), 
	DELIVERYTERM NVARCHAR2(250), 
	DELIVERYPLACE NVARCHAR2(250), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ASSET
--------------------------------------------------------

  CREATE TABLE ASSET 
   (	ASSETID NUMBER(8,0), 
	NAME NVARCHAR2(255), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table BUDGET
--------------------------------------------------------

  CREATE TABLE BUDGET 
   (	BUDGETID NUMBER(8,0), 
	ADMINISTRATIVEUNITID NUMBER(8,0), 
	CODE NVARCHAR2(250), 
	DESCRIPTION NVARCHAR2(550), 
	SEASON NVARCHAR2(25), 
	AMOUNT NUMBER(10,4), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table CHAPTER
--------------------------------------------------------

  CREATE TABLE CHAPTER 
   (	CHAPTERID NUMBER(8,0), 
	BUDGETID NUMBER(8,0), 
	CODE NVARCHAR2(35), 
	CONCEPT NVARCHAR2(250), 
	AMOUNT NUMBER(10,4), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table COMPETITOR
--------------------------------------------------------

  CREATE TABLE COMPETITOR 
   (	COMPETITORID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	SUPPLIERID NUMBER(8,0), 
	TRADENUMBER NVARCHAR2(150), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table CONTRACT
--------------------------------------------------------

  CREATE TABLE CONTRACT 
   (	CONTRACTID NUMBER(8,0), 
	COMPETITORID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	TAXID NVARCHAR2(35), 
	SOURCERESOURCE NVARCHAR2(250), 
	NUMBERMATCH NVARCHAR2(250), 
	EMAIL NVARCHAR2(150), 
	MAXAMOUNT NUMBER(10,4), 
	MAXAMOUNTTEXT NVARCHAR2(250), 
	MINAMOUNT NUMBER(10,4), 
	MINAMOUNTTEXT NVARCHAR2(250), 
	MAXAMOUNTIVA NUMBER(10,4), 
	MAXAMOUNTIVATEXT VARCHAR2(250 BYTE), 
	MINAMOUNTIVA NUMBER(10,4), 
	MINAMOUNTIVATEXT NVARCHAR2(250), 
	PHYSICALPERSON NUMBER(8,0), 
	PHYSICALPERSONDATA NVARCHAR2(250), 
	LEGALDEEDNUMBER NVARCHAR2(150), 
	LEGALNOTARYNUMBER NVARCHAR2(150), 
	LEGALSTATE NVARCHAR2(50), 
	LEGALCITY NVARCHAR2(50), 
	LEGALDATE DATE, 
	LEGALDATETEXT NVARCHAR2(150), 
	LEGALAGENTDEEDNUMBER NVARCHAR2(150), 
	LEGALAGENTNOTARYNUMBER NVARCHAR2(150), 
	LEGALAGENTSTATE NVARCHAR2(50), 
	LEGALAGENTCITY NVARCHAR2(50), 
	LEGALAGENTDATE DATE, 
	LEGALAGENTDATETEXT NVARCHAR2(150), 
	DEPOSIT NUMBER(10,4), 
	DEPOSITTEXT NVARCHAR2(250), 
	DEPOSITPERCENT NUMBER(10,4), 
	DEPOSITPERCENTTEXT NVARCHAR2(250), 
	DEPOSITINADVANCE NUMBER(10,4), 
	DEPOSITINADVANCETEXT NVARCHAR2(250), 
	DUEDATE DATE, 
	DUEDATETEXT NVARCHAR2(150), 
	WINNERNAME NVARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table DOCUMENTVARIABLE
--------------------------------------------------------

  CREATE TABLE DOCUMENTVARIABLE 
   (	DOCUMENTVARIABLEID NUMBER(8,0), 
	VARIABLE NVARCHAR2(100), 
	CLASSNAME NVARCHAR2(250), 
	METHODNAME NVARCHAR2(250), 
	ACTIVE NUMBER(8,0), 
	RETURNTYPE NVARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table EMISSION
--------------------------------------------------------

  CREATE TABLE EMISSION 
   (	EMISSIONID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	PLACE NVARCHAR2(250), 
	EMISSIONDATE DATE, 
	DAYSFORPAYMENT NUMBER(8,0), 
	ACTIVE NUMBER(8,0), 
	EMISSIONDATETEXT NVARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ENTRY
--------------------------------------------------------

  CREATE TABLE ENTRY 
   (	ENTRYID NUMBER(8,0), 
	CHAPTERID NUMBER(8,0), 
	CODE NVARCHAR2(35), 
	DESCRIPTION NVARCHAR2(250), 
	AMOUNTALLOCATED NUMBER(10,4), 
	AMOUNTUSED NUMBER(10,4), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table INSTITUTION
--------------------------------------------------------

  CREATE TABLE INSTITUTION 
   (	INSTITUTIONID NUMBER(8,0), 
	NAME NVARCHAR2(250), 
	ADDRESS NVARCHAR2(500), 
	REPRESENTATIVE NVARCHAR2(250), 
	ACCREDITATIONNUMBER NVARCHAR2(100), 
	TAXID NVARCHAR2(25), 
	DESIGNATION NVARCHAR2(50), 
	CREATIONDATE DATE, 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE ITEM 
   (	ITEMID NUMBER(8,0), 
	PROPOSALID NUMBER(8,0), 
	ANNEXID NUMBER(8,0), 
	UNITPRICE NUMBER(10,4), 
	TOTALAMOUNT NUMBER(10,4), 
	WINNER NUMBER(8,0), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table OPENING
--------------------------------------------------------

  CREATE TABLE OPENING 
   (	OPENINGID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	DENOMINATION NVARCHAR2(150), 
	EVENTDATE DATE, 
	EVENTDATETEXT NVARCHAR2(150), 
	EVENTSTARTHOUR NVARCHAR2(15), 
	EVENTSTARTHOURTEXT NVARCHAR2(150), 
	EVENTENDHOUR NVARCHAR2(15), 
	EVENTENDHOURTEXT NVARCHAR2(150), 
	RESPONSABLE NVARCHAR2(250), 
	FIRSTWITNESS NVARCHAR2(250), 
	SECONDWITNESS NVARCHAR2(250), 
	SUPPLIERID NUMBER(8,0), 
	FAILUREISSUANCEDATE DATE, 
	FAILUREISSUANCEDATETEXT NVARCHAR2(150), 
	FAILUREISSUANCEHOUR NVARCHAR2(15), 
	FAILUREISSUANCEHOURTEXT NVARCHAR2(150), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table PROPOSAL
--------------------------------------------------------

  CREATE TABLE PROPOSAL 
   (	PROPOSALID NUMBER(8,0), 
	COMPETITORID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	TECHNICALSUBMITTED NVARCHAR2(30), 
	TECHNICALREMARK NVARCHAR2(250), 
	ECONOMICSUBMITTED NVARCHAR2(30), 
	ECONOMICREMARK NVARCHAR2(250), 
	TOTALAMOUNT NUMBER(10,4), 
	STATUS NVARCHAR2(30), 
	WINNER NUMBER(8,0), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table QUOTATION
--------------------------------------------------------

  CREATE TABLE QUOTATION 
   (	QUOTATIONID NUMBER(8,0), 
	ADJUDICATIONID NUMBER(8,0), 
	DEMANDING NVARCHAR2(250), 
	DEMANDINGJOB NVARCHAR2(250), 
	AUTHORIZER NVARCHAR2(250), 
	AUTHORIZERJOB NVARCHAR2(250), 
	ELABORATIONDATE DATE, 
	ELABORATIONDATETEXT NVARCHAR2(150), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table QUOTATIONDETAIL
--------------------------------------------------------

  CREATE TABLE QUOTATIONDETAIL 
   (	QUOTATIONDETAILID NUMBER(8,0), 
	QUOTATIONID NUMBER(8,0), 
	COMPETITORID NUMBER(8,0), 
	QUOTATIONDATE DATE, 
	QUOTATIONDATETEXT NVARCHAR2(150), 
	CREDITCONDITION NVARCHAR2(500), 
	DELIVERYTERM NVARCHAR2(250), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table REQUEST
--------------------------------------------------------

  CREATE TABLE REQUEST 
   (	REQUESTID NUMBER(8,0), 
	ENTRYID NUMBER(8,0), 
	CODE NVARCHAR2(35), 
	STATUS NVARCHAR2(25), 
	AMOUNT NUMBER(10,4), 
	CREATIONDATE DATE, 
	CLOSEDATE DATE, 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table REQUESTDETAIL
--------------------------------------------------------

  CREATE TABLE REQUESTDETAIL 
   (	REQUESTDETAILID NUMBER(8,0), 
	REQUESTID NUMBER(8,0), 
	ASSET NVARCHAR2(550), 
	QUANTITY NUMBER(8,0), 
	UNITPRICE NUMBER(10,4), 
	TOTAL NUMBER(10,4), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE ROLE 
   (	ROLEID NUMBER(8,0), 
	NAME NVARCHAR2(50), 
	DESCRIPTION NVARCHAR2(250), 
	ACTIVE NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE SUPPLIER 
   (	SUPPLIERID NUMBER(8,0), 
	NAME NVARCHAR2(250), 
	ADDRESS NVARCHAR2(500), 
	CITY NVARCHAR2(35), 
	STATE NVARCHAR2(35), 
	ZIPCODE NVARCHAR2(10), 
	ACTIVE NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table USERDATA
--------------------------------------------------------

  CREATE TABLE USERDATA 
   (	USERDATAID NUMBER(8,0), 
	NICKNAME NVARCHAR2(50), 
	NAME NVARCHAR2(250), 
	PASSWORD NVARCHAR2(150), 
	ACTIVE NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table USERDATA_ADMINISTRATIVEUNIT
--------------------------------------------------------

  CREATE TABLE USERDATA_ADMINISTRATIVEUNIT 
   (	USERDATAID NUMBER(8,0), 
	ADMINISTRATIVEUNITID NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Table USERDATA_ROLE
--------------------------------------------------------

  CREATE TABLE USERDATA_ROLE 
   (	USERDATAID NUMBER(8,0), 
	ROLEID NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ADJUDICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ADJUDICATION ON ADJUDICATION (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_ADJUDICATION_ADJUDIC01
--------------------------------------------------------

  CREATE INDEX IXFK_ADJUDICATION_ADJUDIC01 ON ADJUDICATIONDOCUMENT (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ADJUDICATIONDOCUMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ADJUDICATIONDOCUMENT ON ADJUDICATIONDOCUMENT (ADJUDICATIONDOCUMENTID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ADJUDICATION_STEP
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ADJUDICATION_STEP ON ADJUDICATIONSTEP (ADJUDICATIONSTEPID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ADMINISTRATI_01
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ADMINISTRATI_01 ON ADMINISTRATIVEUNIT (ADMINISTRATIVEUNITID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_ANNEX_ADJUDICATION
--------------------------------------------------------

  CREATE INDEX IXFK_ANNEX_ADJUDICATION ON ANNEX (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_ANNEX_ASSET
--------------------------------------------------------

  CREATE INDEX IXFK_ANNEX_ASSET ON ANNEX (ASSETID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ANNEX
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ANNEX ON ANNEX (ANNEXID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ASSET
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ASSET ON ASSET (ASSETID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_BUDGET_ADMINISTRATIVEUNIT
--------------------------------------------------------

  CREATE INDEX IXFK_BUDGET_ADMINISTRATIVEUNIT ON BUDGET (ADMINISTRATIVEUNITID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_BUDGET
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_BUDGET ON BUDGET (BUDGETID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_CHAPTER_BUDGET
--------------------------------------------------------

  CREATE INDEX IXFK_CHAPTER_BUDGET ON CHAPTER (BUDGETID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_CHAPTER
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CHAPTER ON CHAPTER (CHAPTERID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_COMPETITOR_ADJUDICATION
--------------------------------------------------------

  CREATE INDEX IXFK_COMPETITOR_ADJUDICATION ON COMPETITOR (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_COMPETITOR_SUPPLIER
--------------------------------------------------------

  CREATE INDEX IXFK_COMPETITOR_SUPPLIER ON COMPETITOR (SUPPLIERID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_TABLE1
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_TABLE1 ON COMPETITOR (COMPETITORID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_CONTRACT_ADJUDICATION
--------------------------------------------------------

  CREATE INDEX IXFK_CONTRACT_ADJUDICATION ON CONTRACT (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_CONTRACT_COMPETITOR
--------------------------------------------------------

  CREATE INDEX IXFK_CONTRACT_COMPETITOR ON CONTRACT (COMPETITORID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_CONTRACT
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CONTRACT ON CONTRACT (CONTRACTID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_DOCUMENTVARIABLE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_DOCUMENTVARIABLE ON DOCUMENTVARIABLE (DOCUMENTVARIABLEID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_EMISSION_ADJUDICATION
--------------------------------------------------------

  CREATE INDEX IXFK_EMISSION_ADJUDICATION ON EMISSION (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_EMISSION
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_EMISSION ON EMISSION (EMISSIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_ENTRY_CHAPTER
--------------------------------------------------------

  CREATE INDEX IXFK_ENTRY_CHAPTER ON ENTRY (CHAPTERID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ENTRY
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ENTRY ON ENTRY (ENTRYID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_INSTITUTION
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_INSTITUTION ON INSTITUTION (INSTITUTIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_ITEM_ANNEX
--------------------------------------------------------

  CREATE INDEX IXFK_ITEM_ANNEX ON ITEM (ANNEXID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_ITEM_PROPOSAL
--------------------------------------------------------

  CREATE INDEX IXFK_ITEM_PROPOSAL ON ITEM (PROPOSALID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ITEM ON ITEM (ITEMID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_OPENING_ADJUDICATION
--------------------------------------------------------

  CREATE INDEX IXFK_OPENING_ADJUDICATION ON OPENING (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_OPENING_SUPPLIER
--------------------------------------------------------

  CREATE INDEX IXFK_OPENING_SUPPLIER ON OPENING (SUPPLIERID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_OPENING
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_OPENING ON OPENING (OPENINGID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_PROPOSAL_ADJUDICATION
--------------------------------------------------------

  CREATE INDEX IXFK_PROPOSAL_ADJUDICATION ON PROPOSAL (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_PROPOSAL_COMPETITOR
--------------------------------------------------------

  CREATE INDEX IXFK_PROPOSAL_COMPETITOR ON PROPOSAL (COMPETITORID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_PROPOSAL
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_PROPOSAL ON PROPOSAL (PROPOSALID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_QUOTATION_ADJUDICATION
--------------------------------------------------------

  CREATE INDEX IXFK_QUOTATION_ADJUDICATION ON QUOTATION (ADJUDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_QUOTATION
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_QUOTATION ON QUOTATION (QUOTATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_QUOTATIONDETAIL_COMP01
--------------------------------------------------------

  CREATE INDEX IXFK_QUOTATIONDETAIL_COMP01 ON QUOTATIONDETAIL (COMPETITORID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_QUOTATIONDETAIL_QUOTATION
--------------------------------------------------------

  CREATE INDEX IXFK_QUOTATIONDETAIL_QUOTATION ON QUOTATIONDETAIL (QUOTATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_QUOTATIONDET_01
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_QUOTATIONDET_01 ON QUOTATIONDETAIL (QUOTATIONDETAILID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_REQUEST_ENTRY
--------------------------------------------------------

  CREATE INDEX IXFK_REQUEST_ENTRY ON REQUEST (ENTRYID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_REQUEST
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_REQUEST ON REQUEST (REQUESTID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_REQUESTDETAIL_REQUEST
--------------------------------------------------------

  CREATE INDEX IXFK_REQUESTDETAIL_REQUEST ON REQUESTDETAIL (REQUESTID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_REQUESTDETAI_01
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_REQUESTDETAI_01 ON REQUESTDETAIL (REQUESTDETAILID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_ROLE ON ROLE (ROLEID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_SUPPLIER
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_SUPPLIER ON SUPPLIER (SUPPLIERID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index PK_UserData
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_UserData ON USERDATA (USERDATAID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_USERDATA_ADM_ADMINIS01
--------------------------------------------------------

  CREATE INDEX IXFK_USERDATA_ADM_ADMINIS01 ON USERDATA_ADMINISTRATIVEUNIT (ADMINISTRATIVEUNITID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_USERDATA_ADMINI_USER01
--------------------------------------------------------

  CREATE INDEX IXFK_USERDATA_ADMINI_USER01 ON USERDATA_ADMINISTRATIVEUNIT (USERDATAID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_UserData_Role_Role
--------------------------------------------------------

  CREATE INDEX IXFK_UserData_Role_Role ON USERDATA_ROLE (ROLEID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Index IXFK_UserData_Role_UserData
--------------------------------------------------------

  CREATE INDEX IXFK_UserData_Role_UserData ON USERDATA_ROLE (USERDATAID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
--------------------------------------------------------
--  DDL for Trigger TRG_ADJUDICATION_ADJUDICATIONID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_ADJUDICATION_ADJUDICATIONID 
	BEFORE INSERT 
	ON ADJUDICATION 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_ADJUDICATION_ADJUDICATIONID.NEXTVAL 
		INTO :NEW.ADJUDICATIONID 
		FROM DUAL; 
	END;
/
ALTER TRIGGER TRG_ADJUDICATION_ADJUDICATIONID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ADJUDICATIONDOCUMENT_ADJUDICATIONDOCUMENTID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_ADJUDICATIONDOCUMENT_ADJUDICATIONDOCUMENTID 
	BEFORE INSERT 
	ON ADJUDICATIONDOCUMENT 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_ADJUDICATIONDOCUMENT_ADJUDICATIONDOCUMENTID.NEXTVAL 
		INTO :NEW.ADJUDICATIONDOCUMENTID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_ADJUDICATIONDOCUMENT_ADJUDICATIONDOCUMENTID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ADJUDICATIONSTEP_ADJUDICATIONSTEPID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_ADJUDICATIONSTEP_ADJUDICATIONSTEPID 
	BEFORE INSERT 
	ON ADJUDICATIONSTEP 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_ADJUDICATIONSTEP_ADJUDICATIONSTEPID.NEXTVAL 
		INTO :NEW.ADJUDICATIONSTEPID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_ADJUDICATIONSTEP_ADJUDICATIONSTEPID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ADMINISTRATIVEUNIT_ADMINISTRATIVEUNITID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_ADMINISTRATIVEUNIT_ADMINISTRATIVEUNITID 
	BEFORE INSERT 
	ON ADMINISTRATIVEUNIT 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_ADMINISTRATIVEUNIT_ADMINISTRATIVEUNITID.NEXTVAL 
		INTO :NEW.ADMINISTRATIVEUNITID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_ADMINISTRATIVEUNIT_ADMINISTRATIVEUNITID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ANNEX_ANNEXID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_ANNEX_ANNEXID 
	BEFORE INSERT 
	ON ANNEX 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_ANNEX_ANNEXID.NEXTVAL 
		INTO :NEW.ANNEXID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_ANNEX_ANNEXID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ASSET_ASSETID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_ASSET_ASSETID 
	BEFORE INSERT 
	ON ASSET 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_ASSET_ASSETID.NEXTVAL 
		INTO :NEW.ASSETID
		FROM DUAL; 
	END;
/
ALTER TRIGGER TRG_ASSET_ASSETID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BUDGET_BUDGETID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_BUDGET_BUDGETID 
	BEFORE INSERT 
	ON BUDGET 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_BUDGET_BUDGETID.NEXTVAL 
		INTO :NEW.BUDGETID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_BUDGET_BUDGETID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CHAPTER_CHAPTERID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_CHAPTER_CHAPTERID 
	BEFORE INSERT 
	ON CHAPTER 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_CHAPTER_CHAPTERID.NEXTVAL 
		INTO :NEW.CHAPTERID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_CHAPTER_CHAPTERID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_COMPETITOR_COMPETITORID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_COMPETITOR_COMPETITORID 
	BEFORE INSERT 
	ON COMPETITOR 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_COMPETITOR_COMPETITORID.NEXTVAL 
		INTO :NEW.COMPETITORID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_COMPETITOR_COMPETITORID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CONTRACT_CONTRACTID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_CONTRACT_CONTRACTID 
	BEFORE INSERT 
	ON CONTRACT 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_CONTRACT_CONTRACTID.NEXTVAL 
		INTO :NEW.CONTRACTID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_CONTRACT_CONTRACTID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DOCUMENTVARIABLE_DOCUMENTVARIABLEID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_DOCUMENTVARIABLE_DOCUMENTVARIABLEID 
	BEFORE INSERT 
	ON DOCUMENTVARIABLE 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_DOCUMENTVARIABLE_DOCUMENTVARIABLEID.NEXTVAL 
		INTO :NEW.DOCUMENTVARIABLEID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_DOCUMENTVARIABLE_DOCUMENTVARIABLEID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMISSION_EMISSIONID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_EMISSION_EMISSIONID 
	BEFORE INSERT 
	ON EMISSION 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_EMISSION_EMISSIONID.NEXTVAL 
		INTO :NEW.EMISSIONID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_EMISSION_EMISSIONID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ENTRY_ENTRYID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_ENTRY_ENTRYID 
	BEFORE INSERT 
	ON ENTRY 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_ENTRY_ENTRYID.NEXTVAL 
		INTO :NEW.ENTRYID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_ENTRY_ENTRYID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INSTITUTION_INSTITUTIONID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_INSTITUTION_INSTITUTIONID 
	BEFORE INSERT 
	ON INSTITUTION 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_INSTITUTION_INSTITUTIONID.NEXTVAL 
		INTO :NEW.INSTITUTIONID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_INSTITUTION_INSTITUTIONID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ITEM_ITEMID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_ITEM_ITEMID 
	BEFORE INSERT 
	ON ITEM 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_ITEM_ITEMID.NEXTVAL 
		INTO :NEW.ITEMID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_ITEM_ITEMID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_OPENING_OPENINGID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_OPENING_OPENINGID 
	BEFORE INSERT 
	ON OPENING 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_OPENING_OPENINGID.NEXTVAL 
		INTO :NEW.OPENINGID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_OPENING_OPENINGID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PROPOSAL_PROPOSALID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_PROPOSAL_PROPOSALID 
	BEFORE INSERT 
	ON PROPOSAL 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_PROPOSAL_PROPOSALID.NEXTVAL 
		INTO :NEW.PROPOSALID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_PROPOSAL_PROPOSALID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_QUOTATION_QUOTATIONID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_QUOTATION_QUOTATIONID 
	BEFORE INSERT 
	ON QUOTATION 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_QUOTATION_QUOTATIONID.NEXTVAL 
		INTO :NEW.QUOTATIONID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_QUOTATION_QUOTATIONID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_QUOTATIONDETAIL_QUOTATIONDETAILID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_QUOTATIONDETAIL_QUOTATIONDETAILID 
	BEFORE INSERT 
	ON QUOTATIONDETAIL 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_QUOTATIONDETAIL_QUOTATIONDETAILID.NEXTVAL 
		INTO :NEW.QUOTATIONDETAILID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_QUOTATIONDETAIL_QUOTATIONDETAILID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_REQUEST_REQUESTID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_REQUEST_REQUESTID 
	BEFORE INSERT 
	ON REQUEST 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_REQUEST_REQUESTID.NEXTVAL 
		INTO :NEW.REQUESTID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_REQUEST_REQUESTID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_REQUESTDETAIL_REQUESTDETAILID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_REQUESTDETAIL_REQUESTDETAILID 
	BEFORE INSERT 
	ON REQUESTDETAIL 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_REQUESTDETAIL_REQUESTDETAILID.NEXTVAL 
		INTO :NEW.REQUESTDETAILID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_REQUESTDETAIL_REQUESTDETAILID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_Role_ROLEID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_Role_ROLEID 
	BEFORE INSERT 
	ON ROLE 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_Role_ROLEID.NEXTVAL 
		INTO :NEW.ROLEID 
		FROM DUAL; 
	END;

/
ALTER TRIGGER TRG_Role_ROLEID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SUPPLIER_SUPPLIERID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_SUPPLIER_SUPPLIERID 
	BEFORE INSERT 
	ON SUPPLIER 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_SUPPLIER_SUPPLIERID.NEXTVAL 
		INTO :NEW.SUPPLIERID 
		FROM DUAL; 
	END;
/
ALTER TRIGGER TRG_SUPPLIER_SUPPLIERID ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_UserData_USERDATAID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER TRG_UserData_USERDATAID 
	BEFORE INSERT 
	ON USERDATA 
	FOR EACH ROW 
	BEGIN 
		SELECT SEQ_UserData_USERDATAID.NEXTVAL 
		INTO :NEW.USERDATAID 
		FROM DUAL; 
	END;
/
ALTER TRIGGER TRG_UserData_USERDATAID ENABLE;
--------------------------------------------------------
--  Constraints for Table ADJUDICATION
--------------------------------------------------------

  ALTER TABLE ADJUDICATION MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (PROCEDURENUMBER NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (CONTRACTTYPE NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (MODALITY NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (SOURCEORIGIN NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (ADJUDICATIONTYPE NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (AMOUNT NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (STATUS NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (CREATIONDATE NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE ADJUDICATION ADD CONSTRAINT PK_ADJUDICATION PRIMARY KEY (ADJUDICATIONID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ADJUDICATIONDOCUMENT
--------------------------------------------------------

  ALTER TABLE ADJUDICATIONDOCUMENT MODIFY (ADJUDICATIONDOCUMENTID NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONDOCUMENT MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONDOCUMENT MODIFY (IDENTIFIER NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONDOCUMENT MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONDOCUMENT MODIFY (PATH NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONDOCUMENT ADD CONSTRAINT PK_ADJUDICATIONDOCUMENT PRIMARY KEY (ADJUDICATIONDOCUMENTID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ADJUDICATIONSTEP
--------------------------------------------------------

  ALTER TABLE ADJUDICATIONSTEP MODIFY (ADJUDICATIONSTEPID NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONSTEP MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONSTEP MODIFY (STEP NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONSTEP MODIFY (CREATIONDATE NOT NULL ENABLE);
  ALTER TABLE ADJUDICATIONSTEP ADD CONSTRAINT PK_ADJUDICATION_STEP PRIMARY KEY (ADJUDICATIONSTEPID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMINISTRATIVEUNIT
--------------------------------------------------------

  ALTER TABLE ADMINISTRATIVEUNIT MODIFY (ADMINISTRATIVEUNITID NOT NULL ENABLE);
  ALTER TABLE ADMINISTRATIVEUNIT MODIFY (CODE NOT NULL ENABLE);
  ALTER TABLE ADMINISTRATIVEUNIT MODIFY (DESCRIPTION NOT NULL ENABLE);
  ALTER TABLE ADMINISTRATIVEUNIT MODIFY (AUTHORIZER NOT NULL ENABLE);
  ALTER TABLE ADMINISTRATIVEUNIT MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE ADMINISTRATIVEUNIT ADD CONSTRAINT PK_ADMINISTRATI_01 PRIMARY KEY (ADMINISTRATIVEUNITID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ANNEX
--------------------------------------------------------

  ALTER TABLE ANNEX MODIFY (ANNEXID NOT NULL ENABLE);
  ALTER TABLE ANNEX MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE ANNEX MODIFY (ASSETID NOT NULL ENABLE);
  ALTER TABLE ANNEX MODIFY (QUANTITY NOT NULL ENABLE);
  ALTER TABLE ANNEX MODIFY (DELIVERYTERM NOT NULL ENABLE);
  ALTER TABLE ANNEX MODIFY (DELIVERYPLACE NOT NULL ENABLE);
  ALTER TABLE ANNEX MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE ANNEX ADD CONSTRAINT PK_ANNEX PRIMARY KEY (ANNEXID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSET
--------------------------------------------------------

  ALTER TABLE ASSET MODIFY (ASSETID NOT NULL ENABLE);
  ALTER TABLE ASSET MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE ASSET MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE ASSET ADD CONSTRAINT PK_ASSET PRIMARY KEY (ASSETID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table BUDGET
--------------------------------------------------------

  ALTER TABLE BUDGET MODIFY (BUDGETID NOT NULL ENABLE);
  ALTER TABLE BUDGET MODIFY (ADMINISTRATIVEUNITID NOT NULL ENABLE);
  ALTER TABLE BUDGET MODIFY (CODE NOT NULL ENABLE);
  ALTER TABLE BUDGET MODIFY (DESCRIPTION NOT NULL ENABLE);
  ALTER TABLE BUDGET MODIFY (SEASON NOT NULL ENABLE);
  ALTER TABLE BUDGET MODIFY (AMOUNT NOT NULL ENABLE);
  ALTER TABLE BUDGET MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE BUDGET ADD CONSTRAINT PK_BUDGET PRIMARY KEY (BUDGETID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAPTER
--------------------------------------------------------

  ALTER TABLE CHAPTER MODIFY (CHAPTERID NOT NULL ENABLE);
  ALTER TABLE CHAPTER MODIFY (BUDGETID NOT NULL ENABLE);
  ALTER TABLE CHAPTER MODIFY (CODE NOT NULL ENABLE);
  ALTER TABLE CHAPTER MODIFY (CONCEPT NOT NULL ENABLE);
  ALTER TABLE CHAPTER MODIFY (AMOUNT NOT NULL ENABLE);
  ALTER TABLE CHAPTER MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE CHAPTER ADD CONSTRAINT PK_CHAPTER PRIMARY KEY (CHAPTERID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPETITOR
--------------------------------------------------------

  ALTER TABLE COMPETITOR ADD CONSTRAINT PK_TABLE1 PRIMARY KEY (COMPETITORID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
  ALTER TABLE COMPETITOR MODIFY (TRADENUMBER NOT NULL ENABLE);
  ALTER TABLE COMPETITOR MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE COMPETITOR MODIFY (COMPETITORID NOT NULL ENABLE);
  ALTER TABLE COMPETITOR MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE COMPETITOR MODIFY (SUPPLIERID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTRACT
--------------------------------------------------------

  ALTER TABLE CONTRACT MODIFY (CONTRACTID NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (COMPETITORID NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (TAXID NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (SOURCERESOURCE NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (NUMBERMATCH NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (EMAIL NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (MAXAMOUNT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (MAXAMOUNTTEXT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (MINAMOUNT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (MINAMOUNTTEXT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (MAXAMOUNTIVA NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (MAXAMOUNTIVATEXT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (MINAMOUNTIVA NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (MINAMOUNTIVATEXT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (PHYSICALPERSON NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (DEPOSIT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (DEPOSITTEXT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (DEPOSITPERCENT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (DEPOSITPERCENTTEXT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (DEPOSITINADVANCE NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (DEPOSITINADVANCETEXT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (DUEDATE NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (DUEDATETEXT NOT NULL ENABLE);
  ALTER TABLE CONTRACT MODIFY (WINNERNAME NOT NULL ENABLE);
  ALTER TABLE CONTRACT ADD CONSTRAINT PK_CONTRACT PRIMARY KEY (CONTRACTID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENTVARIABLE
--------------------------------------------------------

  ALTER TABLE DOCUMENTVARIABLE MODIFY (DOCUMENTVARIABLEID NOT NULL ENABLE);
  ALTER TABLE DOCUMENTVARIABLE MODIFY (VARIABLE NOT NULL ENABLE);
  ALTER TABLE DOCUMENTVARIABLE MODIFY (CLASSNAME NOT NULL ENABLE);
  ALTER TABLE DOCUMENTVARIABLE MODIFY (METHODNAME NOT NULL ENABLE);
  ALTER TABLE DOCUMENTVARIABLE MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE DOCUMENTVARIABLE ADD CONSTRAINT PK_DOCUMENTVARIABLE PRIMARY KEY (DOCUMENTVARIABLEID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table EMISSION
--------------------------------------------------------

  ALTER TABLE EMISSION MODIFY (EMISSIONDATETEXT NOT NULL ENABLE);
  ALTER TABLE EMISSION MODIFY (EMISSIONID NOT NULL ENABLE);
  ALTER TABLE EMISSION MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE EMISSION MODIFY (PLACE NOT NULL ENABLE);
  ALTER TABLE EMISSION MODIFY (EMISSIONDATE NOT NULL ENABLE);
  ALTER TABLE EMISSION MODIFY (DAYSFORPAYMENT NOT NULL ENABLE);
  ALTER TABLE EMISSION MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE EMISSION ADD CONSTRAINT PK_EMISSION PRIMARY KEY (EMISSIONID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ENTRY
--------------------------------------------------------

  ALTER TABLE ENTRY MODIFY (ENTRYID NOT NULL ENABLE);
  ALTER TABLE ENTRY MODIFY (CHAPTERID NOT NULL ENABLE);
  ALTER TABLE ENTRY MODIFY (CODE NOT NULL ENABLE);
  ALTER TABLE ENTRY MODIFY (DESCRIPTION NOT NULL ENABLE);
  ALTER TABLE ENTRY MODIFY (AMOUNTALLOCATED NOT NULL ENABLE);
  ALTER TABLE ENTRY MODIFY (AMOUNTUSED NOT NULL ENABLE);
  ALTER TABLE ENTRY MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE ENTRY ADD CONSTRAINT PK_ENTRY PRIMARY KEY (ENTRYID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table INSTITUTION
--------------------------------------------------------

  ALTER TABLE INSTITUTION MODIFY (INSTITUTIONID NOT NULL ENABLE);
  ALTER TABLE INSTITUTION MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE INSTITUTION MODIFY (ADDRESS NOT NULL ENABLE);
  ALTER TABLE INSTITUTION MODIFY (REPRESENTATIVE NOT NULL ENABLE);
  ALTER TABLE INSTITUTION MODIFY (ACCREDITATIONNUMBER NOT NULL ENABLE);
  ALTER TABLE INSTITUTION MODIFY (TAXID NOT NULL ENABLE);
  ALTER TABLE INSTITUTION MODIFY (DESIGNATION NOT NULL ENABLE);
  ALTER TABLE INSTITUTION MODIFY (CREATIONDATE NOT NULL ENABLE);
  ALTER TABLE INSTITUTION MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE INSTITUTION ADD CONSTRAINT PK_INSTITUTION PRIMARY KEY (INSTITUTIONID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE ITEM MODIFY (ITEMID NOT NULL ENABLE);
  ALTER TABLE ITEM MODIFY (PROPOSALID NOT NULL ENABLE);
  ALTER TABLE ITEM MODIFY (ANNEXID NOT NULL ENABLE);
  ALTER TABLE ITEM MODIFY (UNITPRICE NOT NULL ENABLE);
  ALTER TABLE ITEM MODIFY (TOTALAMOUNT NOT NULL ENABLE);
  ALTER TABLE ITEM MODIFY (WINNER NOT NULL ENABLE);
  ALTER TABLE ITEM MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (ITEMID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table OPENING
--------------------------------------------------------

  ALTER TABLE OPENING MODIFY (OPENINGID NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (DENOMINATION NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (EVENTDATE NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (EVENTDATETEXT NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (EVENTSTARTHOUR NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (EVENTSTARTHOURTEXT NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (EVENTENDHOUR NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (EVENTENDHOURTEXT NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (RESPONSABLE NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (FIRSTWITNESS NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (SECONDWITNESS NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (SUPPLIERID NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (FAILUREISSUANCEDATE NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (FAILUREISSUANCEDATETEXT NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (FAILUREISSUANCEHOUR NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (FAILUREISSUANCEHOURTEXT NOT NULL ENABLE);
  ALTER TABLE OPENING MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE OPENING ADD CONSTRAINT PK_OPENING PRIMARY KEY (OPENINGID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPOSAL
--------------------------------------------------------

  ALTER TABLE PROPOSAL MODIFY (PROPOSALID NOT NULL ENABLE);
  ALTER TABLE PROPOSAL MODIFY (COMPETITORID NOT NULL ENABLE);
  ALTER TABLE PROPOSAL MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE PROPOSAL MODIFY (TECHNICALSUBMITTED NOT NULL ENABLE);
  ALTER TABLE PROPOSAL MODIFY (ECONOMICSUBMITTED NOT NULL ENABLE);
  ALTER TABLE PROPOSAL MODIFY (TOTALAMOUNT NOT NULL ENABLE);
  ALTER TABLE PROPOSAL MODIFY (STATUS NOT NULL ENABLE);
  ALTER TABLE PROPOSAL MODIFY (WINNER NOT NULL ENABLE);
  ALTER TABLE PROPOSAL MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE PROPOSAL ADD CONSTRAINT PK_PROPOSAL PRIMARY KEY (PROPOSALID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table QUOTATION
--------------------------------------------------------

  ALTER TABLE QUOTATION MODIFY (QUOTATIONID NOT NULL ENABLE);
  ALTER TABLE QUOTATION MODIFY (ADJUDICATIONID NOT NULL ENABLE);
  ALTER TABLE QUOTATION MODIFY (DEMANDING NOT NULL ENABLE);
  ALTER TABLE QUOTATION MODIFY (DEMANDINGJOB NOT NULL ENABLE);
  ALTER TABLE QUOTATION MODIFY (AUTHORIZER NOT NULL ENABLE);
  ALTER TABLE QUOTATION MODIFY (AUTHORIZERJOB NOT NULL ENABLE);
  ALTER TABLE QUOTATION MODIFY (ELABORATIONDATE NOT NULL ENABLE);
  ALTER TABLE QUOTATION MODIFY (ELABORATIONDATETEXT NOT NULL ENABLE);
  ALTER TABLE QUOTATION MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE QUOTATION ADD CONSTRAINT PK_QUOTATION PRIMARY KEY (QUOTATIONID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table QUOTATIONDETAIL
--------------------------------------------------------

  ALTER TABLE QUOTATIONDETAIL MODIFY (QUOTATIONDETAILID NOT NULL ENABLE);
  ALTER TABLE QUOTATIONDETAIL MODIFY (QUOTATIONID NOT NULL ENABLE);
  ALTER TABLE QUOTATIONDETAIL MODIFY (COMPETITORID NOT NULL ENABLE);
  ALTER TABLE QUOTATIONDETAIL MODIFY (QUOTATIONDATE NOT NULL ENABLE);
  ALTER TABLE QUOTATIONDETAIL MODIFY (QUOTATIONDATETEXT NOT NULL ENABLE);
  ALTER TABLE QUOTATIONDETAIL MODIFY (CREDITCONDITION NOT NULL ENABLE);
  ALTER TABLE QUOTATIONDETAIL MODIFY (DELIVERYTERM NOT NULL ENABLE);
  ALTER TABLE QUOTATIONDETAIL MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE QUOTATIONDETAIL ADD CONSTRAINT PK_QUOTATIONDET_01 PRIMARY KEY (QUOTATIONDETAILID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE REQUEST MODIFY (REQUESTID NOT NULL ENABLE);
  ALTER TABLE REQUEST MODIFY (ENTRYID NOT NULL ENABLE);
  ALTER TABLE REQUEST MODIFY (CODE NOT NULL ENABLE);
  ALTER TABLE REQUEST MODIFY (STATUS NOT NULL ENABLE);
  ALTER TABLE REQUEST MODIFY (AMOUNT NOT NULL ENABLE);
  ALTER TABLE REQUEST MODIFY (CREATIONDATE NOT NULL ENABLE);
  ALTER TABLE REQUEST MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE REQUEST ADD CONSTRAINT PK_REQUEST PRIMARY KEY (REQUESTID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUESTDETAIL
--------------------------------------------------------

  ALTER TABLE REQUESTDETAIL MODIFY (REQUESTDETAILID NOT NULL ENABLE);
  ALTER TABLE REQUESTDETAIL MODIFY (REQUESTID NOT NULL ENABLE);
  ALTER TABLE REQUESTDETAIL MODIFY (ASSET NOT NULL ENABLE);
  ALTER TABLE REQUESTDETAIL MODIFY (QUANTITY NOT NULL ENABLE);
  ALTER TABLE REQUESTDETAIL MODIFY (UNITPRICE NOT NULL ENABLE);
  ALTER TABLE REQUESTDETAIL MODIFY (TOTAL NOT NULL ENABLE);
  ALTER TABLE REQUESTDETAIL MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE REQUESTDETAIL ADD CONSTRAINT PK_REQUESTDETAI_01 PRIMARY KEY (REQUESTDETAILID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE ROLE MODIFY (ROLEID NOT NULL ENABLE);
  ALTER TABLE ROLE MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE ROLE MODIFY (DESCRIPTION NOT NULL ENABLE);
  ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE PRIMARY KEY (ROLEID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE SUPPLIER MODIFY (SUPPLIERID NOT NULL ENABLE);
  ALTER TABLE SUPPLIER MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE SUPPLIER MODIFY (ADDRESS NOT NULL ENABLE);
  ALTER TABLE SUPPLIER MODIFY (CITY NOT NULL ENABLE);
  ALTER TABLE SUPPLIER MODIFY (STATE NOT NULL ENABLE);
  ALTER TABLE SUPPLIER MODIFY (ZIPCODE NOT NULL ENABLE);
  ALTER TABLE SUPPLIER MODIFY (ACTIVE NOT NULL ENABLE);
  ALTER TABLE SUPPLIER ADD CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIERID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table USERDATA
--------------------------------------------------------

  ALTER TABLE USERDATA MODIFY (USERDATAID NOT NULL ENABLE);
  ALTER TABLE USERDATA MODIFY (NICKNAME NOT NULL ENABLE);
  ALTER TABLE USERDATA MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE USERDATA MODIFY (PASSWORD NOT NULL ENABLE);
  ALTER TABLE USERDATA ADD CONSTRAINT PK_UserData PRIMARY KEY (USERDATAID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE;
--------------------------------------------------------
--  Constraints for Table USERDATA_ADMINISTRATIVEUNIT
--------------------------------------------------------

  ALTER TABLE USERDATA_ADMINISTRATIVEUNIT MODIFY (USERDATAID NOT NULL ENABLE);
  ALTER TABLE USERDATA_ADMINISTRATIVEUNIT MODIFY (ADMINISTRATIVEUNITID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERDATA_ROLE
--------------------------------------------------------

  ALTER TABLE USERDATA_ROLE MODIFY (USERDATAID NOT NULL ENABLE);
  ALTER TABLE USERDATA_ROLE MODIFY (ROLEID NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADJUDICATIONDOCUMENT
--------------------------------------------------------

  ALTER TABLE ADJUDICATIONDOCUMENT ADD CONSTRAINT FK_ADJUDICATION_ADJUDICATIO_01 FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADJUDICATIONSTEP
--------------------------------------------------------

  ALTER TABLE ADJUDICATIONSTEP ADD CONSTRAINT FK_ADJUDICATION_ADJUDICATIO_02 FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANNEX
--------------------------------------------------------

  ALTER TABLE ANNEX ADD CONSTRAINT FK_ANNEX_ADJUDICATION FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
  ALTER TABLE ANNEX ADD CONSTRAINT FK_ANNEX_ASSET FOREIGN KEY (ASSETID)
	  REFERENCES ASSET (ASSETID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUDGET
--------------------------------------------------------

  ALTER TABLE BUDGET ADD CONSTRAINT FK_BUDGET_ADMINISTRATIVEUNIT FOREIGN KEY (ADMINISTRATIVEUNITID)
	  REFERENCES ADMINISTRATIVEUNIT (ADMINISTRATIVEUNITID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAPTER
--------------------------------------------------------

  ALTER TABLE CHAPTER ADD CONSTRAINT FK_CHAPTER_BUDGET FOREIGN KEY (BUDGETID)
	  REFERENCES BUDGET (BUDGETID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPETITOR
--------------------------------------------------------

  ALTER TABLE COMPETITOR ADD CONSTRAINT FK_COMPETITOR_ADJUDICATION FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
  ALTER TABLE COMPETITOR ADD CONSTRAINT FK_COMPETITOR_SUPPLIER FOREIGN KEY (SUPPLIERID)
	  REFERENCES SUPPLIER (SUPPLIERID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRACT
--------------------------------------------------------

  ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_ADJUDICATION FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
  ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_COMPETITOR FOREIGN KEY (COMPETITORID)
	  REFERENCES COMPETITOR (COMPETITORID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMISSION
--------------------------------------------------------

  ALTER TABLE EMISSION ADD CONSTRAINT FK_EMISSION_ADJUDICATION FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENTRY
--------------------------------------------------------

  ALTER TABLE ENTRY ADD CONSTRAINT FK_ENTRY_CHAPTER FOREIGN KEY (CHAPTERID)
	  REFERENCES CHAPTER (CHAPTERID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_ANNEX FOREIGN KEY (ANNEXID)
	  REFERENCES ANNEX (ANNEXID) ENABLE;
  ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_PROPOSAL FOREIGN KEY (PROPOSALID)
	  REFERENCES PROPOSAL (PROPOSALID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPENING
--------------------------------------------------------

  ALTER TABLE OPENING ADD CONSTRAINT FK_OPENING_ADJUDICATION FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
  ALTER TABLE OPENING ADD CONSTRAINT FK_OPENING_SUPPLIER FOREIGN KEY (SUPPLIERID)
	  REFERENCES SUPPLIER (SUPPLIERID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPOSAL
--------------------------------------------------------

  ALTER TABLE PROPOSAL ADD CONSTRAINT FK_PROPOSAL_ADJUDICATION FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
  ALTER TABLE PROPOSAL ADD CONSTRAINT FK_PROPOSAL_COMPETITOR FOREIGN KEY (COMPETITORID)
	  REFERENCES COMPETITOR (COMPETITORID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUOTATION
--------------------------------------------------------

  ALTER TABLE QUOTATION ADD CONSTRAINT FK_QUOTATION_ADJUDICATION FOREIGN KEY (ADJUDICATIONID)
	  REFERENCES ADJUDICATION (ADJUDICATIONID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUOTATIONDETAIL
--------------------------------------------------------

  ALTER TABLE QUOTATIONDETAIL ADD CONSTRAINT FK_QUOTATIONDETAIL_COMPETITOR FOREIGN KEY (COMPETITORID)
	  REFERENCES COMPETITOR (COMPETITORID) ENABLE;
  ALTER TABLE QUOTATIONDETAIL ADD CONSTRAINT FK_QUOTATIONDETAIL_QUOTATION FOREIGN KEY (QUOTATIONID)
	  REFERENCES QUOTATION (QUOTATIONID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE REQUEST ADD CONSTRAINT FK_REQUEST_ENTRY FOREIGN KEY (ENTRYID)
	  REFERENCES ENTRY (ENTRYID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUESTDETAIL
--------------------------------------------------------

  ALTER TABLE REQUESTDETAIL ADD CONSTRAINT FK_REQUESTDETAIL_REQUEST FOREIGN KEY (REQUESTID)
	  REFERENCES REQUEST (REQUESTID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERDATA_ADMINISTRATIVEUNIT
--------------------------------------------------------

  ALTER TABLE USERDATA_ADMINISTRATIVEUNIT ADD CONSTRAINT FK_USERDATA_ADM_ADMINISTRAT_01 FOREIGN KEY (ADMINISTRATIVEUNITID)
	  REFERENCES ADMINISTRATIVEUNIT (ADMINISTRATIVEUNITID) ENABLE;
  ALTER TABLE USERDATA_ADMINISTRATIVEUNIT ADD CONSTRAINT FK_USERDATA_ADMINI_USERDATA_01 FOREIGN KEY (USERDATAID)
	  REFERENCES USERDATA (USERDATAID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERDATA_ROLE
--------------------------------------------------------

  ALTER TABLE USERDATA_ROLE ADD CONSTRAINT FK_UserData_Role_Role FOREIGN KEY (ROLEID)
	  REFERENCES ROLE (ROLEID) ENABLE;
  ALTER TABLE USERDATA_ROLE ADD CONSTRAINT FK_UserData_Role_UserData FOREIGN KEY (USERDATAID)
	  REFERENCES USERDATA (USERDATAID) ENABLE;
--------------------------------------------------------
--  File created - Thursday-December-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ADJUDICATION_ADJUDICATIONID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_ADJUDICATION_ADJUDICATIONID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 49 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADJUDICATIONDOCUMENT_ADJUDICATIONDOCUMENTID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_ADJUDICATIONDOCUMENT_ADJUDICATIONDOCUMENTID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 170 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADJUDICATIONSTEP_ADJUDICATIONSTEPID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_ADJUDICATIONSTEP_ADJUDICATIONSTEPID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 183 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_AdministrativeUnit_ADMINISTRATIVEUNITID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_AdministrativeUnit_ADMINISTRATIVEUNITID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADMINISTRATIVEUNIT_ADMINISTRATIVEUNITID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_ADMINISTRATIVEUNIT_ADMINISTRATIVEUNITID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ANNEX_ANNEXID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_ANNEX_ANNEXID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 540 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ASSET_ASSETID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_ASSET_ASSETID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 32 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BUDGET_BUDGETID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_BUDGET_BUDGETID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CHAPTER_CHAPTERID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_CHAPTER_CHAPTERID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMPETITOR_COMPETITORID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_COMPETITOR_COMPETITORID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 46 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTRACT_CONTRACTID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_CONTRACT_CONTRACTID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DOCUMENTVARIABLE_DOCUMENTVARIABLEID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_DOCUMENTVARIABLE_DOCUMENTVARIABLEID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 65 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMISSION_EMISSIONID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_EMISSION_EMISSIONID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 32 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ENTRY_ENTRYID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_ENTRY_ENTRYID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INSTITUTION_INSTITUTIONID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_INSTITUTION_INSTITUTIONID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ITEM_ITEMID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_ITEM_ITEMID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 848 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_OPENING_OPENINGID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_OPENING_OPENINGID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROPOSAL_PROPOSALID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_PROPOSAL_PROPOSALID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 56 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QUOTATION_QUOTATIONID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_QUOTATION_QUOTATIONID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QUOTATIONDETAIL_QUOTATIONDETAILID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_QUOTATIONDETAIL_QUOTATIONDETAILID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 49 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REQUEST_REQUESTID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_REQUEST_REQUESTID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REQUESTDETAIL_REQUESTDETAILID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_REQUESTDETAIL_REQUESTDETAILID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_Role_ROLEID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_Role_ROLEID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SUPPLIER_SUPPLIERID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_SUPPLIER_SUPPLIERID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_UserData_USERDATAID
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_UserData_USERDATAID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

